# .trivyignore.yaml
#
#vulnerabilities:
#  - id: CVE-2024-1234
#    paths:
#      - usr/bin/some-package
#    reason: "False positive: affects feature we don't use"
#
#  - id: CVE-2024-5678
#    reason: "False positive: requires local access which isn't possible in our container"


secret:
  - id: private-key
    paths:
      - /opt/google-cloud-sdk/platform/gsutil/third_party/urllib3/dummyserver/certs/server.key
    reason: "Test/dummy key in Google Cloud SDK dummyserver, not a real secret"
